tp03-2021/Controllers/CadeteController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using tp03_2021.Entities;
using tp03_2021.Models;
using tp03_2021.ViewModels;

namespace tp03_2021.Controllers
{
    public class CadeteController : Controller
    {
        private readonly RepoCadete _repoCadete;
        private readonly RepoCadeteria _repoCadeteria;
        private readonly IMapper _mapper;
        public CadeteController(RepoCadete repoCadete, IMapper mapper, RepoCadeteria repoCadeteria)
        {
            _repoCadete = repoCadete;
            _mapper = mapper;
            _repoCadeteria = repoCadeteria;
        }

        // GET: CadeteController
        public ActionResult Index()
        {
            try
            {
                if (HttpContext.Session.GetInt32("Rol") >= 2)
                {
                    return View(_repoCadete.getAll());
                }
                
                return View("../Home/Index");
            }
            catch (Exception ex)
            {
                var error = new ErrorViewModel(ex.Message);
                return View("Error", error);
            }
            
        }

        [Route("AltaCadetes")]
        public ActionResult AltaCadete()
        {
            try
            {
                if (HttpContext.Session.GetInt32("Rol") == 3)
                {
                    var cadeteVM = new CadeteViewModel();
                    cadeteVM.Cadeterias = _repoCadeteria.getAll();
                    return View(cadeteVM);
                }
                return View("../Home/Index");
            }
            catch (Exception ex)
            {
                var error = new ErrorViewModel(ex.Message);
                return View("Error", error);
            }

        }

        // POST: CadeteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CrearCadete(CadeteViewModel cadete)
        {
            try
            {
                if (HttpContext.Session.GetInt32("Rol") == 3)
                {
                    _repoCadete.CreateCadete(cadete);
                    return RedirectToAction("AltaCadete");
                }
                return View("../Home/Index");
            }
            catch(Exception ex)
            {
                var error = new ErrorViewModel(ex.Message);
                return View("Error", error);
            }
        }

        // GET: CadeteController/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                if (HttpContext.Session.GetInt32("Rol") >= 2)
                {
                    if (id < 1) return View("Index");
                    var cadete = _repoCadete.getCadeteById(id);
                    var cadeteVM = _mapper.Map<Cadete, CadeteViewModel>(cadete);
                    cadeteVM.Cadeterias = _repoCadeteria.getAll();
                    return View(cadeteVM);
                }
                return View("../Home/Index");
            }
            catch (Exception ex)
            {
                var error = new ErrorViewModel(ex.Message);
                return View("Error", error);
            }

        }

        // POST: CadeteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCadete(CadeteViewModel cadete)
        {
            if (cadete == null)
            {
                return View("Index");
            }
            try
            {
                _repoCadete.UpdateCadete(cadete);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                var error = new ErrorViewModel(ex.Message);
                return View("Error", error);
            }
        }

        // GET: CadeteController/Delete/5
        [HttpPost]
        public IActionResult Delete(int id)
        {
                       
            try
            {
                if (HttpContext.Session.GetInt32("Rol") == 3)
                {
                    if (id < 1) return View("Index");
                    _repoCadete.DeleteCadete(id);
                    return RedirectToAction(nameof(Index));
                }
                return View("../Home/Index");
            }
            catch (Exception ex)
            {
                var error = new ErrorViewModel(ex.Message);
                return View("Error", error);
            }
        }


    }
}

tp03-2021/Controllers/PedidoController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using tp03_2021.Entities;
using tp03_2021.Models;
using tp03_2021.ViewModels;

namespace tp03_2021.Controllers
{
    public class PedidoController : Controller
    {
        private readonly RepoPedido _repoPedido;
        private readonly RepoCadete _repoCadete;
        private readonly RepoCliente _repoCliente;
        private readonly IMapper _mapper;

        public PedidoController(RepoPedido repoPedido, RepoCadete repoCadete, RepoCliente repoCliente, IMapper mapper)
        {
            _repoPedido = repoPedido;
            _repoCadete = repoCadete;
            _repoCliente = repoCliente;
            _mapper = mapper;
        }

        // GET: PedidoController
        public ActionResult Index()
        {
            try
            {
                if (HttpContext.Session.GetInt32("Rol") >= 2)
                {
                    var listadoPedidos = _repoPedido.getAll();
                    return View(listadoPedidos);
                }
                return View("../Home/Index");
            }
            catch (Exception ex)
            {
                var error = new ErrorViewModel(ex.Message);
                return View("Error", error);
            }
                
        }


        public ActionResult AltaPedido()
        {
            try
            {
                if (HttpContext.Session.GetInt32("Rol") >= 1)
                {
                    var pedidoVM = new PedidoViewModel();
                    pedidoVM.Cadetes = _repoCadete.getAll();
                    pedidoVM.Clientes = _repoCliente.getAll();
                    return View(pedidoVM);
                }
                return View("../Home/Index");
            }
            catch (Exception ex)
            {
                var error = new ErrorViewModel(ex.Message);
                return View("Error", error);
            }
            
        }
        // GET: PedidoController/Create
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CrearPedido(PedidoPostViewModel pedidoVM)
        {
            try
            {
                if (HttpContext.Session.GetInt32("Rol") >= 1)
                {
                    _repoPedido.CreatePedido(pedidoVM);
                    return RedirectToAction(nameof(Index));
                }
                return View("../Home/Index");
            }
            catch (Exception ex)
            {
                var error = new ErrorViewModel(ex.Message);
                return View("Error", error);
            }
        }

        // GET: PedidoController/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                if (HttpContext.Session.GetInt32("Rol") >= 2)
                {
                    var pedidoAEditar = _repoPedido.getPedidoById(id);
                    var pedidoVM = _mapper.Map<Pedido, PedidoViewModel>(pedidoAEditar);
                    pedidoVM.Cadetes = _repoCadete.getAll();
                    pedidoVM.Clientes = _repoCliente.getAll();
                    return View(pedidoVM);
                }
                return View("../Home/Index");
            }
            catch (Exception ex)
            {
                var error = new ErrorViewModel(ex.Message);
                return View("Error", error);
            }
                
        }

        // POST: PedidoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPedido(PedidoPostViewModel pedidoVM)
        {
            try
            {
                if (HttpContext.Session.GetInt32("Rol") >= 2)
                {
                    _repoPedido.UpdatePedido(pedidoVM);
                  
                } 
                return RedirectToAction(nameof(Index));
                    
            }
            catch (Exception ex)
            {
                var error = new ErrorViewModel(ex.Message);
                return View("Error", error);
            }
        }

        // GET: PedidoController/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                if (HttpContext.Session.GetInt32("Rol") == 3)
                {
                    _repoPedido.DeletePedido(id);
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                var error = new ErrorViewModel(ex.Message);
                return View("Error", error);
            }

        }

        
    }
}

tp03-2021/Views/Shared/Guest_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"] - WebApplication</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://www.markuptag.com/bootstrap/5/css/bootstrap.min.css">
</head>
<body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                
                <a asp-page="/Index" class="navbar-brand">Cadeteria</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="mt-auto  p-3 mb-1 border-top footer text-muted">
        <div class="container align-content-center">
            &copy; 2021 - Cadeteria <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
   

    <!-- Bootstrap JS -->
    <script src="https://www.markuptag.com/bootstrap/5/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>

tp03-2021/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tp03_2021</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://www.markuptag.com/bootstrap/5/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">tp03_2021</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li>
                            <div class="btn-group">
                                <button type="button" class="btn text-decoration-none dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Cadetes
                                </button>
                                <div class="dropdown-menu text-left">

                                    <a class="nav-link dropdown-item text-dark" asp-area="" asp-controller="Cadete" asp-action="Index">Cadetes</a>

                                    <a class="nav-link dropdown-item" asp-area="" asp-controller="Cadete" asp-action="AltaCadete">Alta de Cadetes</a>

                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="btn-group">
                                <button type="button" class="btn text-decoration-none dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Pedidos
                                </button>
                                <div class="dropdown-menu text-left">

                                    <a class="nav-link dropdown-item text-dark" asp-area="" asp-controller="Pedido" asp-action="Index">Pedidos</a>

                                    <a class="nav-link dropdown-item" asp-area="" asp-controller="Pedido" asp-action="AltaPedido">Crear Pedido</a>

                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="btn-group">
                                <button type="button" class="btn text-decoration-none dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Clientes
                                </button>
                                <div class="dropdown-menu text-left">

                                    <a class="nav-link dropdown-item text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>

                                    <a class="nav-link dropdown-item" asp-area="" asp-controller="Cliente" asp-action="Create">Alta Cliente</a>

                                </div>
                            </div>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - tp03_2021 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://www.markuptag.com/bootstrap/5/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>